const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    FETCH_ALL_CATEGORY_SUCCESS: 'FETCH_ALL_CATEGORY_SUCCESS',
    FETCH_ALL_CATEGORY_FAILED: 'FETCH_ALL_CATEGORY_FAILED',

    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    //CRUD user 
    CREATE_USER_SUCESS: 'CREATE_USER_SUCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    DELETE_USER_SUCESS: 'DELETE_USER_SUCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    EDIT_USER_SUCESS: 'EDIT_USER_SUCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FETCH_ALL_STORIES_SUCCESS: 'FETCH_ALL_STORIES_SUCCESS',
    FETCH_ALL_STORIES_FAILED: 'FETCH_ALL_STORIES_FAILED',

    FETCH_ALL_AUTHORS_SUCCESS: 'FETCH_ALL_AUTHORS_SUCCESS',
    FETCH_ALL_AUTHORS_FAILED: 'FETCH_ALL_AUTHORS_FAILED',

    //CRUD story

    CREATE_STORY_SUCESS: 'CREATE_STORY_SUCESS',
    CREATE_STORY_FAILED: 'CREATE_STORY_FAILED',

    DELETE_STORY_SUCESS: 'DELETE_STORY_SUCESS',
    DELETE_STORY_FAILED: 'DELETE_STORY_FAILED',

    EDIT_STORY_SUCESS: 'EDIT_STORY_SUCESS',
    EDIT_STORY_FAILED: 'EDIT_STORY_FAILED',

    SAVE_DETAIL_STORY_SUCCESS: 'SAVE_DETAIL_STORY_SUCCESS',
    SAVE_DETAIL_STORY_FAILED: 'SAVE_DETAIL_STORY_FAILED',

    //CHAPTER
    FETCH_CHAPTER_START: 'FETCH_CHAPTER_START',
    FETCH_CHAPTER_SUCCESS: 'FETCH_CHAPTER_SUCCESS',
    FETCH_CHAPTER_FAILED: 'FETCH_CHAPTER_FAILED'


})
export default actionTypes;